repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
        exclude: ^\.gitlab-ci.yml$
      - id: pretty-format-json
        args: ["--autofix"]
      - id: detect-private-key
      - id: mixed-line-ending

  # python static type checking
  # Based on: https://jaredkhan.com/blog/mypy-pre-commit
  - repo: local
    hooks:
      - id: mypy
        exclude: (^docs/|conftest\.py)
        name: mypy
        entry: ./run-mypy
        language: system
        types: [python]
        # use require_serial so that script
        # is only called once per commit
        require_serial: true

  # python code formatting
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  # python import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # python upgrading syntax to newer version
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  # python docstring formatting
  - repo: https://github.com/myint/docformatter
    rev: v1.6.5
    hooks:
      - id: docformatter
        args: [--in-place]

  # python check (PEP8), programming errors and code complexity
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  # git commit message lint
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: false
